analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    unnecessary_brace_in_string_interps: ignore
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml
